name: CI/CD NodeJs Backend boilerplate

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install npm dependencies
        run: npm install

      - name: build the project
        run: npm run build
